using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework;
using kata;
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace kata.Tests
{
    public partial class FizzBuzzTest
    {

[TestMethod]
[PexGeneratedBy(typeof(FizzBuzzTest))]
public void Constructor578()
{
    FizzBuzz fizzBuzz;
    fizzBuzz = this.Constructor();
    PexAssert.IsNotNull((object)fizzBuzz);
}
    }
}
